title: Chad Kirk Portfolio Developer Documentation
description: Chad Kirk Portfolio Developer Documentation
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  PicPocket Repository: https://github.com/ChadWKirk/Portfolio
